language: 
 - java
 - node_js

jdk:
  - oraclejdk8

node_js:
  - node

script:
  - build.sh
  - "mvn test -DdatabaseEngine=h2"

branches:
  only:
  - master
  - devel

install:
  - npm install -g gulp gulp-cli
  
after_success:
  - mvn -Pcobertura clean cobertura:cobertura
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report
