language: java

jdk:
  - oraclejdk8

script: "mvn test -DdatabaseEngine=h2"

branches:
  only:
  - master
  - devel
  
before_script:
  - npm install -g gulp
script: gulp

after_success:
  - mvn -Pcobertura clean cobertura:cobertura
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report
